### ISSUE TITLE
Unable to upload after the latest deployment 3.3.2.

### ISSUE THREAD

**Issue by svramu** [Tattvum/edutvum-exam#1]
File upload was working before. Unable to upload after the latest deployment 3.3.2. Some error in console.
[edu.tattvum.com-1551454260877.log](https://github.com/Tattvum/edutvum-exam/files/2923421/edu.tattvum.com-1551454260877.log)

**Comment by svramu** [comment]
3.3.4 Fixed upload bug due to Angular deprecated API. To be deployed and pushed.
(https://stackoverflow.com/a/50661040)
//firebase-storage-getdownloadurl-method-cant-be-resolved
(https://firebase.google.com/docs/storage/web/upload-files#monitor_upload_progress)

Somewhere the old synchronous downloadurl property is deprecated. Now an async method call.
[localhost-1551458027543.log](https://github.com/Tattvum/edutvum-exam/files/2923446/localhost-1551458027543.log)

**Comment by JayasriRamu** [comment]
> File upload was working before. Unable to upload after the latest deployment 3.3.2. Some error in console.
> [edu.tattvum.com-1551454260877.log](https://github.com/Tattvum/edutvum-exam/files/2923421/edu.tattvum.com-1551454260877.log)

**Comment by JayasriRamu** [comment]
Now it is working fine. I can upload the files. thank you.
