### ISSUE TITLE
Allow Chemistry symbols through MathJax

### ISSUE THREAD

**Issue by svramu** [Tattvum/edutvum-exam#6]
Allow Chemistry symbols through MathJax.

**Comment by JayasriRamu** [comment]
// Add the above lines in index.html file
<script type="text/x-mathjax-config"> 
  MathJax.Ajax.config.path["mhchem"] =
  "https://cdnjs.cloudflare.com/ajax/libs/mathjax-mhchem/3.3.2";
MathJax.Hub.Config({
  TeX: {
    extensions: ["[mhchem]/mhchem.js"]
  }
});
</script>

**Comment by svramu** [comment]
Committed and deployed. Thank you.
